job.type: search
search.type: sf

dataset.name: wnrr
model: autosf
valid.metric: mean_reciprocal_rank_filtered

sf_search:
  num_trials: 10
  structure_genarator: random
  K: 4

lookup_embedder:
  class_name: LookupEmbedder
  dim: 128
  dropout: 0.0
  initialize: uniform_
  initialize_args:
    +++: +++
    normal_:
      mean: 0.0
      std: 0.0005472140383629246
    uniform_:
      a: -0.28148249060722197
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  normalize:
    p: -1.0
  pretrain:
    ensure_all: false
    model_filename: ''
  regularize: lp
  regularize_args:
    +++: +++
    p: 2
    weighted: false
  regularize_weight: 0.0
  round_dim_to: []
  sparse: false

train:
  abort_on_nan: true
  auto_correct: true
  batch_size: 512
  checkpoint:
    every: 5
    keep: 3
    keep_init: true
  loss: kl
  loss_arg: 1.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    +++: +++
    factor: 0.95
    mode: max
    patience: 5
    threshold: 0.0001
  lr_warmup: 0
  max_epochs: 200
  num_workers: 0
  optimizer:
    +++: +++
    default:
      args:
        +++: +++
        lr: 0.5255808623927111
      type: Adagrad
  pin_memory: false
  split: train
  subbatch_auto_tune: false
  subbatch_size: -1
  trace_level: epoch
  type: 1vsAll
  visualize_graph: false
training_loss:
  class_name: TrainingLossEvaluationJob
user:
  +++: +++
valid:
  early_stopping:
    patience: 10
    threshold:
      epochs: 50
      metric_value: 0.05
  every: 5
  metric: mean_reciprocal_rank_filtered_with_test
  metric_expr: float("nan")
  metric_max: true
  split: valid
  trace_level: epoch
