job.type: train

dataset.name: wnrr

train:
  type: 1vsAll
  batch_size: 512
  optimizer.default:
    type: Adagrad
    args:
      lr: 0.3
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    mode: max
    patience: 7
  max_epochs: 500

model: complex
lookup_embedder:
  dim: 128
  dropout: 0.05
  regularize_weight: 1.45e-18
  initialize: uniform_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.3
