job.type: train

dataset.name: wnrr

train:
  type: 1vsAll
  batch_size: 512
  optimizer.default:
    type: Adagrad
    args:
      lr: 0.3
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    mode: max
    patience: 4

model: complex
lookup_embedder:
  dim: 128
  regularize_weight: 0.8e-7
  initialize: normal_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.1
