job.type: train

dataset.name: wnrr

train:
  type: 1vsAll
  batch_size: 512
  optimizer.default:
    type: Adagrad
    args:
      lr: 0.3
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    mode: max
    patience: 7
  max_epochs: 500

model: complex
lookup_embedder:
  dim: 128
  dropout: 0.4
  regularize_weight: 1.45e-15
  initialize: uniform_
  initialize_args:
    uniform_:
      a: -0.31
      b: 0.31
